server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/love?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: love
    password: love123456

logging:
  level:
    web: debug