server:
  port: 8888
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
      protocol-header-https-value: https
#      remote-ip-header: x-forwarded-for
#      port-header: X-Forwarded-Port
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/love?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: love
    password: love123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    web: debug